---
title: "Resampling (ISLR Ch 5)"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    css: DrDstyle.css
    toc: yes
    toc_float: true
    toc_depth: 2
always_allow_html: true
---

# Part I: In class shared learning


## [Introduction and the validation set approach. (ISLR 5.1.1)](https://youtu.be/ngrOYWgJjb4) (14:01)

1. What are the two most commonly used resampling methods? 
2. The process of evaluating a model’s performance is known as ____. 
3. The process of selecting the proper level of flexibility for a model is known as _____. 
4. The training error typically ______ estimates the test error rate. 
5. What is the main reason to use cross-validation? 
6. What is the main reason to use bootstrap? 
7. As the model complexity increases, what happens to the training and testing errors? 
8. Why is the bias low for models with high complexity? 
9. What is a validation set? 
10. Describe the validation process. 
11. What are the drawbacks of the validation set approach? 


## [Cross-Validation (ISLR 5.1) ](https://youtu.be/rSGzUy13F_0) (13:33)

_The video talks about k-fold validation first, but it's second in the text_. 

### LOOCF (5.1.2)
1. How is LOOCF a special case of CV? 
2. What is a drawback of LOOCF when $n$ is large? 
3. When would we only care about the location of the minimum point in the test MSE curve, and not the actual value of the minimum MSE itself? 

### k-Fold Cross-Validation (5.1.3)
1. Describe the process of K-fold cross validation. 
2. _In English_  how do you calculate the cross-validation error rate? 


### Bias-Variance trade-off for k-Fold CV (5.1.4)
1. Why does k-fold CV give more accurate estimates of the test error rate than LOOCF? Explain this in English. 
2. What is a good value for $k$ that will result in test error rates that find a nice balance between bias and variance? 

## [Right and wrong way to do cross-validation](https://www.youtube.com/watch?v=r64tRyHFAJ8&list=PL5-da3qGB5IA6E6ZNXu7dp89_uv8yocmf&index=3) (10:07)

_I'm not sure this section is in the book_

1. Why can't you do variable selection (model selection) on the full data before building a classification model that includes cross-validation? 
2. Explain how to do variable selection correctly. 


## [The Bootstrap (ISLR 5.2)](https://www.youtube.com/watch?v=p4BYWX7PTBM&list=PL5-da3qGB5IA6E6ZNXu7dp89_uv8yocmf&index=4) (11:29) 

1. The bootstrap is a powerful method for estimating _____? 
2. Instead of using the population estimates for the variance and the covariance, what do you use instead? 
3. How does creating a bootstrap sample different from creating the sampling distribution? 
4. Why do some observations appear more than once in a given bootstrap sample? 


## [The Real world vs the Bootstrap world](https://www.youtube.com/watch?v=uX5kPAK0lpo&list=PL5-da3qGB5IA6E6ZNXu7dp89_uv8yocmf&index=5) (14:35)

1. Can you use the bootstrap with time series or autocorrelated data? 
2. How can you estimate 95% confidence intervals using the bootstrap?
3. Can the bootstrap estimate prediction error?


----

# Part II: Exercises / Learning Tidymodels

You have been provided a separate document containing the resampling assignment from Spring 2020 that builds a classification model using the `caret` package [(vignette)](https://topepo.github.io/caret/). Replicate the steps in this document on a new data set (using the same header structure) in a new Rmarkdown document, using the tidymodels framework. To keep this assignment reasonble and to not get lost in the data preparation, choose a new data set from the caret vignette: https://topepo.github.io/caret/data-sets.html 

Some steps may not apply, or work in the same manner. Not all steps are appropriate to be converted. For each step examine what is being shown, think about the purpose, and decide how you want to replicate it. This is part of the learning. Can you see how someone else approached a question and can you replicate it? 

This assignment is a classification task. Your goal is to build a model to predict the _class_ of a record. Recall that a _class_ is a level of a categorical variable such as `major`, which holds values of `math`, `biology`, and `psychology`. A binary indicator variable such as `smoking_status` that has values `1` for _smoker_ and `0` for _non-smoker_ is also considered a classification problem. 






